name: Stuff
on: [pull_request, merge_group]
jobs:
  chill:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 120 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '120s'
